# Site settings
name: "Café Nordlys"
description: 'A minimal, single-column Jekyll theme that provides an immersive read experience for your readers'
#port: 4001
#baseurl: '/' # the subpath of your site, e.g. /blog
url: 'http://cafenordlys.github.io/' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: false
        # Meta
        show_tags: false
        show_categories: false
        # Social
        share_buttons: false
        disqus: false

